### ISSUE TITLE
Implement a mechanism to refresh pages occationally

### ISSUE THREAD

**Issue by debloper** [debloper/piosk#10]
Rudimentary time or counter based mechanisms are okay, until a more reliable or per-URL conditional can be thought of.

**Comment by andiohn** [comment]
You could always run a refresh button press like you do with the switcher. Call it 'refresh.sh'. Then if you can parse how many tabs are open and what the current switcher delay is, you could trigger the script to run with those inputs.

Let "Number of tabs in dashboard" = NoTiDb
Let "Switch Time" = Switchtime

1. Refresh script is triggered
2. Deactivate switcher.sh for ( NoTiDb * Switchtime + 20 seconds?)
3. Press control shift r
4. Wait for 3 seconds less than Switchtime
5. Press control tab
6. Repeat 3 and 4 until NoTiDb is reached
7. Switcher.sh loops again

Or you could add it to switcher where the X amount of cycles through switcher, adds a refresh. That is probably better.
