### ISSUE TITLE
Modify the how to to add hostname change. I borked my install by changing the hostname after the script ran

### ISSUE THREAD

**Issue by andiohn** [debloper/piosk#20]
If you add 'update hostname if you're planning to' to the preparation section, that'd be enough.

**Comment by debloper** [comment]
Will add emphasis on setting a hostname before running the script, BUT:

I'm curious... were you able to access it over the IP based URL? I understand that change of hostname can cause weird issues (discovery, caching, OS specific discrepancy etc) but the IP based URL still should work. The IP should also work for SSH as well. If not, then that's a problem we need to fix.

If you could please explain how your setup got borked after hostname change, that'd help understand & resolve the issue. Thanks again!

**Comment by andiohn** [comment]
Hey sorry, I didn't notice the question. Ya, the web interface worked fine, but it wouldn't open the browser. I also noticed other browser based issues, where it would just not launch the browser, so I have to figure that out still. The only thing I could think of is the hostname because it happened after.
