### ISSUE TITLE
Option to "hardcode" display resolution with cmdline.txt and config.txt

### ISSUE THREAD

**Issue by andiohn** [debloper/piosk#39]
I found that it's not smart to run at 4k on a display, so I just hard code this to 1080 with 32 bit depth. Perhaps an enhancement in the interface would be a check box to choose a resolution to hard code. If the check box is checked off, then show a drop down with the options. When we apply the options, change the cmdline.txt and/or config.txt to the option selected. 

That way, even if the display doesn't come back up, they can just try what they like and if they don't need 32 bit depth, then they can choose that instead. 

I could force the resolution but I couldn't figure out how to force the bit depth too, so I had to go back to the auto setting. :/

**Comment by andiohn** [comment]
AH! I found it. Wayfire.ini settings can set a resolution. 

https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/configuration/display-resolution.adoc

**Comment by andiohn** [comment]
Turns out that most of what I'm talking about can be configured via the wayfire.ini! Like power on button and other things.

**Comment by andiohn** [comment]
Ya, that worked great. I wonder if we could set the overlay partition to read only and still edit the wayfire.ini. Or if we could have it read a setting from the webserver so we can keep read only on. 

Anyways, wayfire.ini lets you set the resolution and now I basically have a digital signage player that should be relatively reliable...

**Comment by debloper** [comment]
Good find, and thanks for adding in the details for anyone looking for it.

When the dashboard page is having an overhaul, this may be one of the configuration that makes into it.

**Comment by andiohn** [comment]
I couldn't set the bit depth though, still have to figure that out. Seems stuck at 16bit
