### ISSUE TITLE
File based 'included defaults', like a clock that runs on device, or a gallery that displays any image in a folder...

### ISSUE THREAD

**Issue by andiohn** [debloper/piosk#42]
I already wrote a 'burn-in free clock' that looks decent. I could write more little html pages to run as the default. It would be really cool to slowly make some good examples that can be hacked around to do different things. 

Also, this would be a good project to display home assistant dashboards too perhaps.

**Comment by andiohn** [comment]
Also, one of the default ones, like the clock or something could detect if the network is down and display 'no network' on the website too.

**Comment by andiohn** [comment]
OH, and another one. It would be good to have chrome in 'night mode' or something so the network down page has a black background.

**Comment by debloper** [comment]
This is the file that feeds the initial default configs: https://github.com/debloper/piosk/blob/main/config.json.sample

Please feel free to submit pull request with changes you deem more fitting. I just put in a few examples at the time to get it started, but it's open to user contribution.

**Comment by andiohn** [comment]
Oh, here is one!

https://github.com/mariosemes/SimpleClockWithDateForScreenSaver

This is a clock and weather I found and it's on github. This could be a really good default addition. And it can run locally. What about one with and one without weather, so the one without weather is literally just a clock...AND it has burn in protection too!

**Comment by andiohn** [comment]
Ok, I have another one for us to use, it's a clock that shows a gallery behind it from a folder all locally. I'm going to find some quick images to put in it, but it will also look at DJI_1111.jpg type files in a folder that you specify with the starting and ending ranges. The theory is you can have 'job' files within the folders you define and you don't have to specify the image names. If it isn't a valid image, it just fades to black. 

Job folder names (currently there is 4) these will look for DJI files within the range that is defined next to it.
images folder, this will look for any file named image1 with jpg jpeg and png extensions and up to a range you define. 

So, basically you can either just use the images folder and put stuff in there or you can use the job folders and dump drone pictures in there. But if you do neither, it'll just display a black background. Oh and it won't display small pictures below 1000x600, so you can change that variable too if your display is smaller.

It's decently hacky but it looks nice. Here is the current code for it, it's just an html. 

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamic Background with Clock and Fade Effect</title>
    <style>
        body {
            margin: 0;
            height: 100vh;
            background-color: black; /* Start with a black background */
            color: white;
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            transition: background-color 1s ease-in-out;
            overflow: hidden;
            position: relative;
        }

        /* Clock styling with transparency */
        .clock {
            font-size: 15vw;
            margin-bottom: 1rem;
            z-index: 10; /* Ensure clock is always visible above background */
            color: rgba(255, 255, 255, 0.9); /* 10% transparent */
            text-shadow: 0px 0px 10px rgba(0, 0, 0, 0.7), 0px 0px 20px rgba(0, 0, 0, 0.5); /* Black shadow */
        }

        .date {
            font-size: 4vw;
            z-index: 10; /* Ensure date is always visible above background */
            color: rgba(255, 255, 255, 0.9); /* Same transparency */
            text-shadow: 0px 0px 10px rgba(0, 0, 0, 0.7), 0px 0px 20px rgba(0, 0, 0, 0.5); /* Black shadow */
        }

        /* Smooth fade for background image transitions */
        .background-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-size: cover;
            background-position: center;
            opacity: 0;
            transition: opacity 2s ease-in-out;
            animation: kenBurns 20s forwards linear; /* 20s for slower effect */
        }

        /* Ken Burns effect without reverse */
        @keyframes kenBurns {
            0% {
                background-size: 100%;
                background-position: center center;
            }
            50% {
                background-size: 115%;
                background-position: center 10%;
            }
            100% {
                background-size: 130%;
                background-position: center 20%;
            }
        }

        /* Ensure image is visible when fully loaded */
        .background-image.show {
            opacity: 1;
        }

    </style>
</head>
<body>
    <div class="clock" id="clock"></div>
    <div class="date" id="date"></div>

    <script>
        // Base folders and image number ranges
        const baseFolders = [
            { folder: 'job 1', range: { start: 1, end: 2 } },
            { folder: 'job 2', range: { start: 1, end: 2 } },
            { folder: 'job 3', range: { start: 1, end: 2 } }
        ];

        // Configurable range for the 'images' folder
        const imagesFolderRange = { start: 1, end: 10 }; // You can change the range here
        const imagesPath = 'images/'; // Path to the images folder
        let lastImage = ''; // Variable to track the last displayed image

        // Check if an image exists and its size is valid
        function imageExists(src) {
            return new Promise((resolve, reject) => {
                const img = new Image();
                img.onload = function() {
                    if (img.width >= 1000 && img.height >= 600) {
                        resolve(true);
                    } else {
                        reject("Image too small");
                    }
                };
                img.onerror = function() {
                    reject("Image failed to load");
                };
                img.src = src;
            });
        }

        // Create an image element and add to the DOM
        function createImageElement() {
            const imgElement = document.createElement('div');
            imgElement.classList.add('background-image');
            document.body.appendChild(imgElement);
            return imgElement;
        }

        // Generate image file names based on folder structure and ranges
        function generateImageList() {
            let imageList = [];
            baseFolders.forEach(folderInfo => {
                const { folder, range } = folderInfo;
                for (let i = range.start; i <= range.end; i++) {
                    let paddedIndex = String(i).padStart(4, '0'); // Pad the number with leading zeros for DJI images
                    imageList.push(`${folder}/DJI_${paddedIndex}.jpg`); // Only .jpg for DJI files
                }
            });

            // Add images from the 'images' folder without padding
            for (let i = imagesFolderRange.start; i <= imagesFolderRange.end; i++) {
                imageList.push(`${imagesPath}image${i}.jpg`);
                imageList.push(`${imagesPath}image${i}.jpeg`);
                imageList.push(`${imagesPath}image${i}.png`);
            }
            return imageList;
        }

        // Lazy load background image by selecting randomly from the list
        async function loadRandomImage() {
            let validImageFound = false;
            let attempts = 0;
            const imgElement = createImageElement(); // Create an empty image element for the background

            let currentImage = '';
            const imageList = generateImageList(); // Get the list of all images
            while (!validImageFound && attempts < 10) {
                // Pick a random image from the list
                const randomIndex = Math.floor(Math.random() * imageList.length);
                currentImage = `${imageList[randomIndex]}`;

                // Ensure the new image is not the same as the last one
                if (currentImage === lastImage) {
                    continue; // Skip if it's the same as the last image
                }

                try {
                    const exists = await imageExists(currentImage);
                    if (exists) {
                        imgElement.style.backgroundImage = `url('${currentImage}')`;
                        imgElement.classList.add('show');
                        validImageFound = true;
                        lastImage = currentImage; // Update last image to the current one
                    }
                } catch (e) {
                    console.error(`Image ${imageList[randomIndex]} not found or too small, trying another.`);
                }
                attempts++;
            }

            if (!validImageFound) {
                // If no valid image found, fade to black background
                console.error("No valid image found, using black background.");
                imgElement.style.backgroundImage = 'none';
                imgElement.classList.add('show'); // Ensure the background is visible as black
            }
        }

        // Display the current time and date
        function updateClock() {
            const now = new Date();
            const hours = now.getHours();
            const minutes = now.getMinutes();
            const seconds = now.getSeconds();
            const day = now.getDate();
            const month = now.getMonth() + 1; // Months are 0-based
            const year = now.getFullYear();

            // Format time and date
            const timeString = `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
            const dateString = `${month.toString().padStart(2, '0')}/${day.toString().padStart(2, '0')}/${year}`;

            document.getElementById('clock').textContent = timeString;
            document.getElementById('date').textContent = dateString;
        }

        // Call the loadRandomImage function every 15 seconds
        setInterval(loadRandomImage, 15000); // Change image every 15 seconds
        loadRandomImage(); // Initial image load
        setInterval(updateClock, 1000); // Update clock every second
        updateClock(); // Initial clock update
    </script>
</body>
</html>
`

**Comment by andiohn** [comment]
[index.txt](https://github.com/user-attachments/files/17962173/index.txt)

This is the file. I made it today, the license for it is whatever license is here for Piosk.

**Comment by andiohn** [comment]
Quick improvement incoming. I'm changing the date to be human friendly and to have it move slowly so to not cause burn in. I think it's working pretty good.

Improvement - Make it check the size of the viewport and don't display images that are below a percentage of the size of the viewport. That way it doesn't have to be updated to a hard amount but can be dynamic on what would look good. 

[index.txt](https://github.com/user-attachments/files/17962279/index.txt)

**Comment by andiohn** [comment]
Lets grab some pictures from here for examples https://unsplash.com/s/photos/open-source and then perhaps a couple explaining pictures.

1. Put your own files in \images named image1.jpg or image2.png to have them display. It will, by default, display images with those names and extensions of jpg jpeg and png up to image10
2. Or put your files in \job 1\DJI_2333.jpg or jpeg. This will display drone images. You can set the range to what's valid 2333 to 2444 for instance.
3. There is also job 2 and job 3 by default but you can add more if you like. 
4. This will display just black background if you don't put any pictures in it.

That's basically how to use it. It's local only, so it works without the internet.

**Comment by andiohn** [comment]
I'd like one to also do the same thing with videos, grab a random 10 seconds of a video in those folders too but that's beyond me right now.

**Comment by andiohn** [comment]
Also, I think it's super inefficient? I'm going to try it on a Pi 2 W and see how it goes. We could also break out the settings into the management interface, or set up something that checks the files that exist and then just uses those, but I'm not that good yet. :)

**Comment by andiohn** [comment]
I wonder if it would make sense to have the 'defaults' in their own repo? Or perhaps an issue type on here, so it can be split off from actual issues?
